[project]
name = "streamlit-mh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.58.0",
    "google-generativeai>=0.8.0",
    "gtts>=2.5.4",
    "streamlit-mic-recorder>=0.0.8",
    "google-genai>=2.10.0",
    "pandas>=3.0.3",
    "numpy>=2.5.1",
    "matplotlib>=3.11.0",
    "scikit-learn>=1.9.0",
    "folium>=0.20.0",
    "streamlit-folium>=0.27.2",
    "requests>=2.34.2",
    "streamlit-js-eval>=1.0.0",
    "openpyxl>=3.1.5",
    "streamlit-autorefresh>=1.0.1",
]
